// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AudioConfig {
  alert_file: string;
  alert_volume: number;
  alert_repeat: number;
}
