// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intent } from "./Intent";
import type { SessionType } from "./SessionType";

export interface CreateTimerSession {
  _type: SessionType;
  duration: number;
  intent: Intent;
}
