// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateSession {
  duration: number;
  summary: string | null;
  started_at: number;
  intent_id: number;
}
