// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetTasksOptions {
  intent_id: number | null;
  offset: number | null;
  limit: number | null;
  completed: boolean | null;
}
