// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface InterfaceConfig {
  display_timer_countdown: boolean;
  idle_theme_id: string;
  focus_theme_id: string;
  break_theme_id: string;
  long_break_theme_id: string;
}
