// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Intent {
  id: number;
  label: string;
  pinned: boolean;
  created_at: number;
  archived_at: number;
}
