// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IntentForUpdate {
  label: string | null;
  pinned: boolean | null;
  tags: Array<string> | null;
  objective: string | null | null;
  description: string | null;
}
