// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Intent {
  id: string;
  label: string;
  pinned: boolean;
  created_at: string;
  archived_at: string | null;
}
