// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Note {
  id: string;
  body: string;
  intent_id: string | null;
  created_at: string;
  modified_at: string;
}
