// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intent } from "./Intent";

export interface QueueSession {
  intent: Intent;
  duration: number;
  iterations: number;
}
