// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QueueSession {
  id: string;
  project_id: string | null;
  duration: number;
  cycles: number;
}
