// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Script {
  id: string;
  body: string;
  active: boolean;
  run_on_session_start: boolean;
  run_on_session_pause: boolean;
  run_on_session_end: boolean;
  run_on_break_start: boolean;
  run_on_break_pause: boolean;
  run_on_break_end: boolean;
}
