// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Script {
  id: number;
  label: string;
  body: string;
  enabled: boolean;
  exec_on_session_start: boolean;
  exec_on_session_pause: boolean;
  exec_on_session_complete: boolean;
  exec_on_break_start: boolean;
  exec_on_break_pause: boolean;
  exec_on_break_complete: boolean;
}
