// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ScriptForUpdate {
  label: string | null;
  body: string | null;
  active: boolean | null;
  run_on_session_start: boolean | null;
  run_on_session_pause: boolean | null;
  run_on_session_end: boolean | null;
  run_on_break_start: boolean | null;
  run_on_break_pause: boolean | null;
  run_on_break_end: boolean | null;
}
