// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Session {
  id: number;
  duration: number;
  summary: string | null;
  started_at: number;
  finished_at: number;
  intent_id: number;
}
