// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Session {
  id: string;
  started_at: string;
  finished_at: string;
  project_id: string | null;
  duration: number;
}
