// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SessionForCreate {
  started_at: string;
  project_id: string | null;
  duration: number;
}
