// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SessionForCreate {
  duration: number;
  intent_id: string | null;
  started_at: string;
}
