// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SettingsConfigForUpdate {
  idle_theme_id?: number;
  focus_theme_id?: number;
  break_theme_id?: number;
  long_break_theme_id?: number;
  alert_file?: string;
  alert_volume?: number;
  alert_repeat?: number;
  system_notifications?: boolean;
  main_minimize_to_tray?: boolean;
  main_always_on_top?: boolean;
  main_display_on_timer_complete?: boolean;
}
