// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Settings {
  pomodoro_duration: bigint;
  break_duration: bigint;
  long_break_duration: bigint;
  long_break_interval: bigint;
  auto_start_pomodoros: boolean;
  auto_start_breaks: boolean;
  alert_name: string;
  alert_path: string;
  alert_volume: bigint;
  alert_repeat: bigint;
}
