// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SettingsForUpdate {
  pomodoro_duration?: number;
  break_duration?: number;
  long_break_duration?: number;
  long_break_interval?: number;
  auto_start_pomodoros?: boolean;
  auto_start_breaks?: boolean;
  alert_audio?: string;
  alert_volume?: number;
  alert_repeat?: number;
  current_theme_id?: string;
  current_project_id: string | null;
}
