// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intent } from "./Intent";
import type { SessionQueue } from "./SessionQueue";

export interface StateForUpdate {
  session_queue: SessionQueue | null | null;
  active_intent: Intent | null | null;
}
