// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Task {
  id: number;
  body: string;
  completed: boolean;
  created_at: Date;
  finished_at: Date;
  intent_id: number;
}
