// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Task {
  id: string;
  body: string;
  done: boolean;
  intent_id: string | null;
  created_at: string;
  finished_at: string | null;
}
