// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Theme {
  id: number;
  label: string;
  favorite: boolean;
  window_hex: string;
  base_hex: string;
  text_hex: string;
  primary_hex: string;
  variant: string;
}
