// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TimerConfigForUpdate {
  focus_duration?: number;
  break_duration?: number;
  long_break_duration?: number;
  long_break_interval?: number;
  auto_start_focus?: boolean;
  auto_start_breaks?: boolean;
}
