// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intent } from "./Intent";
import type { SessionType } from "./SessionType";

export interface TimerSession {
  _type: SessionType;
  is_playing: boolean;
  duration: number;
  time_elapsed: number;
  started_at: number;
  intent: Intent;
}
