// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionType } from "./SessionType";

export interface TimerSession {
  _type: SessionType;
  duration: number;
  elapsed_time: number;
  iterations: number;
  is_playing: boolean;
  started_at: string | null;
  intent_id: string | null;
}
