// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TodoForCreate {
  body: string;
  project_id: string | null;
  parent_id: string | null;
}
