// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Todo {
  id: string;
  body: string;
  checked: boolean;
  parent_id: string | null;
  project_id: string | null;
}
