// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TodoForUpdate {
  body?: string;
  project_id?: string;
  parent_id?: string;
}
