// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateTheme {
  label: string | null;
  favorite: boolean | null;
  variant: string | null;
  window_hex: string | null;
  base_hex: string | null;
  text_hex: string | null;
  primary_hex: string | null;
}
