// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateScript {
  label: string | null;
  body: string | null;
  enabled: boolean | null;
  exec_on_session_start: boolean | null;
  exec_on_session_pause: boolean | null;
  exec_on_session_complete: boolean | null;
  exec_on_break_start: boolean | null;
  exec_on_break_pause: boolean | null;
  exec_on_break_complete: boolean | null;
}
